import './burger'
// import './swiper'
// import './sliders'
import './fixedMenu'
//import './scroll'
//import './micromodal'
import './sendAjax'
//import './animate'
// import './pop-ap-services'
// import './antispam'

