// import './burger'
// import './sliders'
import './fixedMenu'
//import './scroll'
//import './micromodal'
// import './sendAjax'
import './pop-ap-services'
// import './antispam'
import './animate'
// import './yandexMaps'
import './swiper'
import "./mobileMenu";
// import './imask'
// import './buttonsPress'
